### PR TITLE
Use ACE editor for JavaScript if app includes it

### PR DESCRIPTION
**Pull request by douglaselee**
Use ACE editor anywhere user can edit JavaScript.
To enable app just needs to include script tags for ACE build (see related pull request in formio-app-formio).
If app doesn't include ACE build then fall back on textarea for editing.
Autocomplete includes API names of form's components (press Ctrl + Space).
Requires related pull request in ngFormio.
See also related pull requests in formio and formio-app-formio.

### CODE REVIEW

**Comment by travist** [comment]
How is this supposed to work? I am trying to run this for our latest app build and it isn't turning these text areas into the ACE editors.

**Comment by douglaselee** [comment]
Hi Travis.

The application needs to include the ACE build.  Textarea is fallback.  See related pull request at formio-app-formio.

**Comment by travist** [comment]
Ah... yeah, got it working. We are going to pull this into our next portal release. Thanks again!

**Comment by douglaselee** [comment]
Happy to help Travis!

**Pull request merged**
