### PR TITLE
Feature/for 447 - Allowing components with lockConfiguration to get unique keys

### PR DESCRIPTION
**Pull request by zackurben**

### CODE REVIEW

**Comment by zackurben** [comment]
closes https://github.com/formio/ngFormBuilder/issues/227

@AbdallaMohamed @andreiho Can one of you confirm that this fixes your issue?

**Comment by andreiho** [comment]
@zackurben I will check it out and let you know.

**Comment by andreiho** [comment]
@zackurben Here a couple of things that I noticed:

- component keys are uniquified when adding them directly, without launching the edit modal, which is good

- the first component of a type being added is not uniquified. Before, the very first textfield component for example would get the key `textField1`. Is that on purpose?

- nested components do not get uniquified if they are added in the config phase. We have a custom container which is configured to contain 3 other components by default. When we drag that custom container, the container itself gets a unique key, however its children do not. [Here is a demo.](https://media.giphy.com/media/3ohzdNbodPQhlFJm3C/giphy.gif)

**Comment by zackurben** [comment]
Hey @andreiho, thanks for the feedback. I have a few things for you:

> the first component of a type being added is not uniquified. Before, the very first textfield component for example would get the key textField1. Is that on purpose?

No, this is not on purpose, I see the issue you're mentioning, and I'll look into fixing it.

> nested components do not get uniquified

I see the gif, but I cant see the component keys. Do the child components get keys? If so what are they, and if you make two of those custom components can you save the form or do you get duplicate key errors on the child (and even parent) components?

**Comment by andreiho** [comment]
The child components get the keys defined in their `settings` object when we register them. However they are never uniquified, because they are never added the traditional way. What we do is register a custom container, and at runtime attach some other components to it by pulling their settings object from the `formioComponents` object.

If I try to save the form with two of those components, I get the duplicate key error on the child components. The parent is unique and it doesn't throw an error. I guess the solution would be to uniquify components recursively, so that when a layout component is being added, its `components` array is also checked and passed through the uniquifier.

**Comment by zackurben** [comment]
@andreiho hmm, I'm curious if any multi-component item automatically uniquifies child keys. Knowing how the uniquify system worked before, I don't think it could have possible worked (aka `Existing Resource Fields` with child components)

Ill see if theres an easy-ish fix

**Comment by zackurben** [comment]
@andreiho I updated the latest code to fix the regression with the initial component not being uniquified

The child component issue is a separate issue that already exists, and it may take a bit longer to fix.

**Comment by andreiho** [comment]
@zackurben Thanks. I checked it out and it's working.

**Comment by zackurben** [comment]
@andreiho try the latest build. It should work for child components too.

**Comment by AbdallaMohamed** [comment]
@zackurben I pulled the latest changes. And child components do get unique keys and everything, but there's a problem with our custom container that contains 3 components by default.

When that container is added for the first time, it gets a unique key as well as its 3 children components, and that is fine.
But when I added a new component (Component A) in that container, it doesn't get a unique key. However, when I add yet another component (Component B) in the container, the old one (Component A) gets the unique key, where as Component B doesn't get the unique key.

mar-24-2017 14-12-24

**Comment by zackurben** [comment]
@AbdallaMohamed Are these new child components (ones not in the custom component already) displaying the config page, or do they have the `lockConfiguration` setting enabled

**Comment by AbdallaMohamed** [comment]
@zackurben Sorry for the late reply. They have their lockConfiguration set to true.

**Comment by zackurben** [comment]
@AbdallaMohamed can you confirm that the expected behavior DOES work for the same situation (nested components) with something like the container component?

I've created a resource with a single container and a few fields, then enabled the `lockConfiguration` setting.

When I drag the existing (container) resource field onto my form, all the of the components have their default key (does not include the # for some reason, tbd), however when I add a duplicate existing resource field, the new component has all uniquified keys, and so on and so forth, without me interacting with the components at all.

I'll look into the initial key iteration issue now

**Comment by zackurben** [comment]
@AbdallaMohamed I fixed the initial key iteration problem. Check if the other issue is fixed too, if not, then try what I proposed above, to see if we can narrow it down to just an issue with custom components.

**Comment by AbdallaMohamed** [comment]
@zackurben Looks like that fixed it! Check the behaviour here: 

mar-30-2017 13-03-56

**Comment by zackurben** [comment]
Great, glad to help! This will be merged in the next build.

**Pull request merged**
